:root { --ink:#102a3a; --muted:#667b88; --line:#dce5e9; --petrol:#063b4b; --petrol-2:#0a5162; --bg:#f3f6f7; --gold:#cf9b34; --orange:#df6f2b; }
* { box-sizing:border-box; }
html, body { margin:0; min-height:100%; background:var(--bg); color:var(--ink); font-family:Arial, Helvetica, sans-serif; }
button, input, select { font:inherit; }
button { cursor:pointer; }
.shell { min-height:100vh; display:flex; }
.sidebar { width:252px; position:fixed; inset:0 auto 0 0; background:linear-gradient(180deg,#073f50,#052f3d); color:white; padding:25px 16px 18px; display:flex; flex-direction:column; z-index:3; }
.brand { display:flex; align-items:center; gap:12px; padding:0 8px 28px; border-bottom:1px solid #ffffff1e; }
.brand-logo { width:42px; height:42px; object-fit:contain; border-radius:50%; background:white; }
.brand strong { font-size:22px; letter-spacing:1.7px; display:block; }.brand span { display:block; font-size:10px; color:#b8ccd2; letter-spacing:.45px; margin-top:2px; }
nav { margin-top:22px; display:grid; gap:4px; }.nav-item { border:0; background:transparent; color:#c6d8dd; min-height:43px; border-radius:8px; display:grid; grid-template-columns:25px 1fr auto; align-items:center; text-align:left; padding:0 12px; font-size:13px; font-weight:600; }.nav-item>span { font-size:18px; color:#94b2ba; }.nav-item:hover,.nav-item:focus-visible { background:#ffffff12; color:white; }.nav-item.active { background:#ffffff18; color:white; box-shadow:inset 3px 0 #e0aa3d; }.nav-item b { background:#d56a2d; min-width:20px; height:20px; padding:0 5px; border-radius:10px; display:grid; place-items:center; font-size:10px; }
.security-card { margin-top:auto; padding:15px; border:1px solid #ffffff1c; background:#ffffff09; border-radius:9px; }.security-card span { font-size:9px; letter-spacing:1.1px; color:#8bd0bd; font-weight:700; }.security-card p { font-size:10px; line-height:1.5; color:#b9cbd0; margin:8px 0 0; }
.profile { display:grid; grid-template-columns:35px 1fr 20px; gap:9px; align-items:center; margin-top:18px; padding:16px 6px 0; border-top:1px solid #ffffff1e; }.avatar { width:34px;height:34px;border-radius:50%;background:#d5a143;color:#173b47;display:grid;place-items:center;font-weight:800;font-size:11px;}.profile strong,.profile span { display:block; white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }.profile strong{font-size:11px}.profile span{font-size:9px;color:#9fb8c0;margin-top:3px}.profile button{background:none;border:0;color:#b7cad0;font-size:18px}
.workspace { width:calc(100% - 252px); margin-left:252px; min-height:100vh; }.topbar { height:72px; padding:0 42px; background:white; border-bottom:1px solid var(--line); display:flex; align-items:center; justify-content:space-between; position:sticky; top:0; z-index:2; }.search { width:min(420px,45vw); display:flex; align-items:center; gap:10px; background:#f4f7f8; border:1px solid #e2e9ec; border-radius:8px; padding:9px 12px; color:#738792; }.search input { flex:1; border:0; outline:0; background:transparent; font-size:12px; color:var(--ink); }.search kbd { font-size:9px; background:white; border:1px solid #d7e0e3; border-radius:4px; padding:3px 5px; }.top-actions{display:flex;align-items:center;gap:9px}.top-actions button{width:34px;height:34px;border:1px solid #dde6e9;background:white;border-radius:8px;color:#57707b}.bell{position:relative}.bell i{position:absolute;right:-3px;top:-4px;background:#d86a2b;color:white;border-radius:50%;font-size:8px;width:15px;height:15px;display:grid;place-items:center;font-style:normal}.role-select{font-size:10px;color:#71858f;display:flex;align-items:center;gap:7px}.role-select select{border:1px solid #dce5e9;border-radius:7px;padding:7px;background:white;color:#284755;font-size:10px}
.content { padding:35px 42px 60px; max-width:1500px; margin:auto; }.welcome-row { display:flex; justify-content:space-between; align-items:end; margin-bottom:28px; }.eyebrow { color:#a06d1c!important; font-size:9px!important; letter-spacing:1.4px; font-weight:800; margin-bottom:7px!important; }.welcome-row h1{font:700 29px Georgia,serif;margin:0;color:#14394a}.welcome-row p{font-size:12px;color:#71838c;margin:8px 0 0}.primary{border:0;border-radius:7px;background:var(--petrol);color:white;padding:11px 17px;font-size:11px;font-weight:700;box-shadow:0 4px 12px #063b4b26}.primary:hover{background:var(--petrol-2)}
.metrics { display:grid; grid-template-columns:repeat(4,1fr); gap:14px; margin-bottom:18px; }.metrics article { background:white; border:1px solid var(--line); border-radius:9px; min-height:111px; padding:20px; display:flex; align-items:center; gap:15px; box-shadow:0 2px 8px #12374608; }.metric-icon{width:41px;height:41px;border-radius:8px;display:grid;place-items:center;font-size:20px}.metric-icon.blue{background:#e2f1f5;color:#1d6c80}.metric-icon.orange{background:#fbebdf;color:#ce6426}.metric-icon.teal{background:#e2f3ee;color:#2d806a}.metric-icon.gold{background:#f8f0db;color:#aa791e}.metrics span,.metrics small{display:block;color:#71838c;font-size:9px}.metrics strong{display:block;font:700 25px Georgia,serif;margin:5px 0;color:#153a49}.metrics small b{color:#2a8667}
.main-grid{display:grid;grid-template-columns:1.65fr 1fr;gap:18px;margin-bottom:18px}.panel{background:white;border:1px solid var(--line);border-radius:9px;box-shadow:0 2px 9px #12374608}.panel-head{padding:19px 21px 15px;display:flex;justify-content:space-between;align-items:start;border-bottom:1px solid #e7edef}.panel-head h2{font:700 16px Georgia,serif;margin:0;color:#173c4b}.panel-head p{margin:5px 0 0;color:#778a93;font-size:9px}.panel-head button{border:0;background:transparent;color:#236379;font-size:10px;font-weight:700;padding:4px}.task-list{padding:3px 20px 10px}.task{width:100%;min-height:61px;border:0;border-bottom:1px solid #edf1f2;background:white;display:grid;grid-template-columns:10px 1fr auto 10px;gap:12px;align-items:center;text-align:left;color:#5d737e}.task:last-child{border-bottom:0}.task:hover{background:#f8fafb}.dot{width:7px;height:7px;border-radius:50%}.dot.gold{background:#d6a241}.dot.blue{background:#3a8498}.dot.orange{background:#db6d2c}.task strong,.task small{display:block}.task strong{font-size:11px;color:#1c3b49}.task small{font-size:9px;color:#82939a;margin-top:5px}.task em{font-style:normal;font-size:8px;padding:4px 7px;border-radius:10px}.task em.gold{background:#f9f0d8;color:#986b17}.task em.blue{background:#e5f2f5;color:#28677a}.task em.orange{background:#fbeddf;color:#b95a22}.empty{font-size:11px;color:#748791;padding:15px}
.calendar-panel{padding-bottom:10px}.agenda-item{display:grid;grid-template-columns:45px 1fr;gap:12px;align-items:center;margin:0 20px;padding:14px 0;border-bottom:1px solid #edf1f2}.agenda-item time{height:43px;border-radius:7px;background:#edf4f6;color:#476875;font-size:8px;display:grid;place-items:center;padding:4px}.agenda-item time b{font:700 17px Georgia,serif;color:#173e4e;line-height:1}.agenda-item strong,.agenda-item span{display:block}.agenda-item strong{font-size:10px;color:#1d3f4d}.agenda-item span{font-size:9px;color:#83949b;margin-top:5px}.calendar-link{display:block;margin:13px auto 2px;border:0;background:transparent;color:#23657b;font-size:9px;font-weight:700}
.commitments-panel{overflow:hidden}.commit-table{padding:0 19px 8px}.tr{width:100%;border:0;border-bottom:1px solid #edf1f2;background:white;display:grid;grid-template-columns:2.1fr 1.4fr .8fr .9fr 20px;gap:12px;align-items:center;text-align:left;padding:12px 5px;color:#667b85;font-size:9px}.tr:not(.th):hover{background:#f8fafb}.tr:not(.th) span:first-child{font-weight:700;color:#1f414f}.tr.th{color:#899ba3;font-size:7px;letter-spacing:.7px;font-weight:700}.status{color:#1d725c!important;background:#e4f2ed;border-radius:10px;padding:4px 8px;width:max-content}.toast{position:fixed;right:25px;bottom:25px;background:#113e4d;color:white;border-left:4px solid #d8a23b;padding:13px 18px;border-radius:7px;box-shadow:0 10px 30px #0a293545;font-size:11px;z-index:8}
@media(max-width:1050px){.metrics{grid-template-columns:repeat(2,1fr)}.main-grid{grid-template-columns:1fr}.sidebar{width:220px}.workspace{width:calc(100% - 220px);margin-left:220px}.content,.topbar{padding-left:25px;padding-right:25px}}
@media(max-width:720px){.sidebar{width:100%;height:68px;bottom:auto;padding:10px 14px;flex-direction:row;align-items:center}.brand{border:0;padding:0}.brand-mark{width:36px;height:36px;font-size:21px}.sidebar nav,.security-card,.profile{display:none}.workspace{width:100%;margin:68px 0 0}.topbar{height:60px;padding:0 14px}.search{width:65vw}.search kbd,.role-select{display:none}.content{padding:24px 14px 95px}.welcome-row{align-items:start}.welcome-row h1{font-size:24px}.welcome-row p{max-width:220px;line-height:1.5}.metrics{grid-template-columns:1fr 1fr;gap:9px}.metrics article{padding:13px;min-height:95px}.metric-icon{display:none}.main-grid{gap:12px}.commit-table{overflow-x:auto}.tr{min-width:650px}.primary{position:fixed;bottom:18px;left:18px;right:18px;z-index:4}.panel-head{padding:17px}.task-list{padding:3px 14px}.toast{left:18px;right:18px;bottom:75px}.top-actions button:first-of-type{display:none}}
