"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { SpeechTextarea } from "@/components/speech-textarea";

export function ReclamoForm({ companies }: { companies: { id:string|number; nombre:string }[] }) {
  const router=useRouter(); const[saving,setSaving]=useState(false); const[message,setMessage]=useState<{type:"success"|"error";text:string}|null>(null);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setMessage(null);const form=event.currentTarget;const data=new FormData(form);const optional=(name:string)=>String(data.get(name)||"").trim()||null;const supabase=createClient();const{error}=await supabase.from("reclamos_sindicales").insert({titulo:String(data.get("titulo")||"").trim(),empresa_nombre:optional("empresa_nombre"),lugar:optional("lugar"),fecha_hecho:optional("fecha_hecho"),categoria:optional("categoria"),descripcion:String(data.get("descripcion")||"").trim(),prioridad:String(data.get("prioridad")||"normal"),estado:"abierto",fecha_limite:optional("fecha_limite")});setSaving(false);if(error){setMessage({type:"error",text:`No se pudo guardar: ${error.message}`});return}form.reset();setMessage({type:"success",text:"Reclamo registrado correctamente."});router.refresh()}
  return <form className="claim-form" onSubmit={save}><div className="claim-grid"><label>Título<input name="titulo" required maxLength={180}/></label><label>Empresa<select name="empresa_nombre" defaultValue=""><option value="">Sin empresa / no corresponde</option>{companies.map(company=><option key={company.id} value={company.nombre}>{company.nombre}</option>)}</select></label></div><div className="claim-grid three"><label>Categoría<select name="categoria" defaultValue="laboral"><option value="laboral">Laboral</option><option value="salarial">Salarial</option><option value="higiene_seguridad">Higiene y seguridad</option><option value="obra_social">Obra social</option><option value="afiliacion">Afiliación</option><option value="otro">Otro</option></select></label><label>Prioridad<select name="prioridad" defaultValue="normal"><option value="baja">Baja</option><option value="normal">Normal</option><option value="alta">Alta</option><option value="urgente">Urgente</option></select></label><label>Fecha del hecho<input name="fecha_hecho" type="date"/></label></div><div className="claim-grid"><label>Lugar<input name="lugar" maxLength={180}/></label><label>Fecha límite<input name="fecha_limite" type="date"/></label></div><SpeechTextarea label="Descripción del reclamo" name="descripcion" rows={7}/><button type="submit" disabled={saving}>{saving?"Guardando...":"Registrar reclamo"}</button>{message&&<p className={message.type} role="status">{message.text}</p>}<style jsx>{`
    .claim-form{display:grid;gap:17px;padding:24px;border:1px solid var(--linea);border-radius:14px;background:white}.claim-grid{display:grid;grid-template-columns:1fr 1fr;gap:15px}.claim-grid.three{grid-template-columns:repeat(3,1fr)}label{display:grid;gap:7px;color:#173b49;font-size:14px;font-weight:900}input,select{width:100%;padding:12px;border:1px solid #aebfc4;border-radius:8px;background:white;color:#173b49;font:16px/1.4 inherit}.claim-form>button{width:fit-content;min-height:46px;padding:12px 20px;border:0;border-radius:8px;background:#0b5264;color:white;font-family:inherit;font-weight:900;cursor:pointer}.claim-form>button:disabled{opacity:.65}.claim-form>p{margin:0;padding:12px 14px;border-radius:8px;font-size:14px;font-weight:800}.claim-form>p.success{background:#e6f5ef;color:#124f3e}.claim-form>p.error{background:#fff0ed;color:#812f24}:global(:root[data-theme="dark"]) .claim-form{background:#18343e;border-color:#49636c}:global(:root[data-theme="dark"]) label{color:#f2f7f8}:global(:root[data-theme="dark"]) input,:global(:root[data-theme="dark"]) select{background:#0b222a;border-color:#5f7b84;color:#f5f8f9}@media(max-width:750px){.claim-form{padding:18px}.claim-grid,.claim-grid.three{grid-template-columns:1fr}.claim-form>button{width:100%}}
  `}</style></form>;
}
